kind: Service
apiVersion: v1
metadata:
  name: lagos-schedule-service
spec:
  type: NodePort
  selector:
    app: lagos-schedule
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: lagos-schedule-deployment
  labels:
    app: lagos-schedule
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lagos-schedule
  template:
    metadata:
      labels:
        app: lagos-schedule
    spec:
      containers:
      - name: lagos-schedule
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8080
